---
- name: Remove Fedora Docker dnf packages
  dnf:
    state: absent
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine

- rpm_key: key=https://download.docker.com/linux/fedora/gpg
    state=present

- copy: src=docker-ce.repo 
    dest=/etc/yum.repos.d/docker-ce.repo
    owner=root group=root mode=644

- name: Install Docker CE
  dnf:
    state: latest
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose

- group: name=docker system=yes

- user: name=docker group=docker create_home=no system=yes shell=/sbin/nologin

- name: Append group docker to "{{ ansible_env.SUDO_USER }}"
  user: 
    name: "{{ ansible_env.SUDO_USER }}"
    groups: docker
    append: yes

- name: Add docker group to sesseion
  shell: "newgrp docker"
  become: yes
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Start Docker CE
  systemd: 
    name: docker.service
    enabled: yes
    daemon_reload: yes
    state: started

- name: Configure firewall for Docker network
  shell: "firewall-cmd --permanent --zone=docker --add-masquerade && firewall-cmd --permanent --zone=docker --add-interface=docker0 && firewall-cmd --set-default-zone=public && firewall-cmd --reload"

- copy: src=docker-daemon.json
    dest=/etc/docker/daemon.json
    owner=root group=root mode=644

- name: Creates "/opt/lazydocker/{{ lazydocker.version }}" directory
  file:
    path: "/opt/lazydocker/{{ lazydocker.version }}"
    state: directory
    mode: 0775

- name: Install Lazydocker
  unarchive:
    src: https://github.com/jesseduffield/lazydocker/releases/download/v{{ lazydocker.version }}/lazydocker_{{ lazydocker.version }}_Linux_x86_64.tar.gz
    remote_src: yes
    dest: "/opt/lazydocker/{{ lazydocker.version }}"
    creates: "/opt/lazydocker/{{ lazydocker.version }}/lazydocker"

- name: Copy Lazydocker bin
  copy:
    dest: /usr/local/bin
    src: "/opt/lazydocker/{{ lazydocker.version }}/lazydocker"
    force: yes
    mode: a+x
