---
- name: Kafkacat is installed
  shell: test -x /usr/local/bin/kafkacat && echo "true" || echo "false"
  ignore_errors: yes
  register: kafkacat_installed

- name: Copy Kafkacat from debezium docker image
  shell: (docker pull debezium/tooling:1.1 && docker run --rm -v /home/{{ ansible_env.SUDO_USER }}/.local/bin:/m debezium/tooling:1.1 sh -c "cp /usr/bin/kafkacat /m/")
  when: kafkacat_installed.stdout == "false"
