---
- include: system.yml
  tags:
    - system

- include: aws.yml
  tags:
    - third-party
    - aws

- include: fedy.yml
  tags:
    - third-party
    - fedy

- include: chrome.yml
  tags:
    - third-party
    - chrome

- include: vscode.yml
  tags:
    - third-party
    - vscode

- include: docker.yml
  tags:
    - third-party
    - docker

- include: kubernetes.yml
  tags:
    - third-party
    - kubernetes

- include: php.yml
  tags:
    - php

- include: java.yml
  tags:
    - java

- include: kafka.yml
  tags:
    - third-party
    - kafka

- include: terraform.yml
  tags:
    - third-party
    - terraform

- name: Install Snap packages
  snap:
    classic: false
    name:
      - 1password
      - spotify
      - zoom-client
      - teams

- name: Install Snap packages on Classic
  snap:
    classic: true
    name:
      - slack
      - postman
