---
- name: Install Remi repo
  dnf:
    name: "http://rpms.remirepo.net/fedora/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: present

- name: Enable Remi repo
  command: dnf config-manager --set-enabled remi
  args:
    warn: no

- name: Install PHP
  dnf:
    state: present
    name:
      - php80
      - php80-runtime
      - php80-php-mbstring
      - php80-php-xml
      - php80-php-cli
      - php80-php-pdo
      - php80-php-json
      - php80-php-intl
      - php80-php-pecl-apcu
      - php80-php-pecl-yaml
      - php80-php-pecl-xdebug
      - php80-php-pecl-rdkafka
      # - php80-php-pecl-imagick
      - php74
      - php74-runtime
      - php74-php-mbstring
      - php74-php-xml
      - php74-php-cli
      - php74-php-pdo
      - php74-php-json
      - php74-php-intl
      - php74-php-pecl-apcu
      - php74-php-pecl-yaml
      - php74-php-pecl-xdebug
      - php74-php-pecl-rdkafka
      # - php74-php-pecl-imagick
      - php73
      - php73-runtime
      - php73-php-mbstring
      - php73-php-xml
      - php73-php-cli
      - php73-php-pdo
      - php73-php-json
      - php73-php-intl
      - php73-php-pecl-apcu
      - php73-php-pecl-yaml
      - php73-php-pecl-xdebug
      - php73-php-pecl-rdkafka
      # - php73-php-pecl-imagick
      - php72
      - php72-php-mbstring
      - php72-php-xml
      - php72-php-cli
      - php72-php-pdo
      - php72-php-json
      - php72-php-intl
      - php72-php-pecl-apcu
      - php72-php-pecl-yaml
      - php72-php-pecl-xdebug
      - php72-php-pecl-rdkafka
      # - php72-php-pecl-imagick

# for now, go execute `sudo ./install-composer.sh` manually
# - name: Install Composer
#   script: install-composer.sh
#   become: yes
#   become_user: "{{ ansible_env.SUDO_USER }}"
#   args:
#     creates: "/usr/local/bin/composer"
