---
- name: disable static motd file
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "PrintMotd"
    line: "PrintMotd no"
  notify:
    - restart sshd

- name: Install neofetch
  dnf: name=neofetch state=latest

- name: Update profile with neofetch
  lineinfile:
    dest: "/etc/profile"
    insertafter: EOF
    line: /usr/bin/neofetch

# - name: Add rpmfusion free
#   dnf:
#     name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
#     state: present

# - name: Add rpmfusion nonfree
#   dnf:
#     name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
#     state: present

- name: Update and upgrade system
  dnf: name=* state=latest
  tags: update

- name: Install dnf packages
  dnf:
    name: "{{ dnf_packages }}"
    state: installed
  tags: pkg

- name: Install rpmfusion packages
  dnf:
    name: "{{ rpmfusion_packages }}"
    state: installed
  tags: pkg

- name: Set Snap to classic mode
  file:
    path: /snap
    src: /var/lib/snapd/snap
    force: yes
    state: link
    follow: yes
