---
- rpm_key: key=https://packages.microsoft.com/keys/microsoft.asc
    state=present

- copy: src=microsoft-vscode.repo 
    dest=/etc/yum.repos.d/vscode.repo
    owner=root group=root mode=644

- name: Install Visual Studio Code
  dnf: pkg=code state=latest

- name: Install vscode extensions
  command: code --install-extension {{ item }}
  with_items:
    # the basics to survive before the sync settings kicks in
    - k--kato.intellij-idea-keybindings
    - Shan.code-settings-sync
  become: yes
  become_user: "{{ ansible_env.SUDO_USER }}"

# - name: Install GitHub CLI
#   dnf:
#     name: https://github.com/cli/cli/releases/download/v{{ gh_cli.version }}/gh_{{ gh_cli.version }}_linux_amd64.rpm
#     state: latest
