---
- name: Install extensions
  dnf:
    state: installed
    name:
      - gnome-shell-extension-user-theme
      - gnome-shell-extension-places-menu

- name: Enable extensions
  shell: gnome-shell-extension-tool -e {{ item }} || true
  with_items:
    - nohotcorner@azuri.free.fr
    - user-theme@gnome-shell-extensions.gcampax.github.com
    - TopIcons@phocean.net
    - places-menu@gnome-shell-extensions.gcampax.github.com
  become: yes
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Disable extensions
  shell: gnome-shell-extension-tool -d {{ item }}  || true
  with_items:
    - background-logo@fedorahosted.org
    - launch-new-instance@gnome-shell-extensions.gcampax.github.com
    - window-list@gnome-shell-extensions.gcampax.github.com
  become: yes
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Creates "/home/{{ ansible_env.USERNAME }}/.local/share/fonts" directory
  file:
    path: /home/{{ ansible_env.USERNAME }}/.local/share/fonts
    state: directory
    owner: '{{ ansible_env.USERNAME }}'
    group: '{{ ansible_env.USERNAME }}'
    mode: 0775

- name: Install JetBrains Mono font
  unarchive:
    src: https://download-cdn.jetbrains.com/fonts/JetBrainsMono-2.242.zip
    remote_src: yes
    dest: /home/{{ ansible_env.USERNAME }}/.local/share/fonts
    owner: '{{ ansible_env.USERNAME }}'
    group: '{{ ansible_env.USERNAME }}'

- name: Refresh system fonts
  command: "fc-cache -f -v"

- name: Enable Fedora Copr for user501254/Arc
  command: "dnf copr enable -y user501254/Arc"
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:user501254:Arc.repo
    warn: false

- name: Install theme packages
  dnf:
    state: installed
    name:
      - arc-icon-theme
      - arc-theme-solid

- name: gsettings set {{ item }}
  command: "gsettings set {{ item }}"
  become: yes
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: ["gsettings"]
  with_items:
    - "{{ gsettings }}"

- name: Load dconf settings from {{ role_path }}/files/
  shell: "dconf load / < {{ role_path }}/files/{{ item }}"
  become: yes
  become_user: "{{ ansible_env.SUDO_USER }}"
  tags: ["dconf"]
  with_items: 
    - gnome.dconf
    - extensions.dconf
