---

- name: Creates Workspace directory
  file:
    path: /home/{{ ansible_env.USERNAME }}/Workspace
    state: directory
    owner: '{{ ansible_env.USERNAME }}'
    group: '{{ ansible_env.USERNAME }}'
    mode: 0775

- name: Creates Workspace Groups directory
  file:
    path: /home/{{ ansible_env.USERNAME }}/Workspace/{{ item }}
    state: directory
    owner: '{{ ansible_env.USERNAME }}'
    group: '{{ ansible_env.USERNAME }}'
    mode: 0775
  with_items:
    - "{{ worspace_dirs }}"

- name: Include vars
  include_vars:
    file: /home/{{ ansible_env.USERNAME }}/.workspace_repos.yaml
    name: workspace_repos_home
  ignore_errors: yes

- name: Clone favorite Open Source projects
  git:
    repo: "{{ item.repo }}"
    dest: "/home/{{ ansible_env.USERNAME }}/Workspace/{{ item.group }}/{{ item.dir }}"
    remote: "{{ item.remote | default('upstream') }}"
    clone: yes
    update: yes
    force: no
  ignore_errors: yes
  with_items:
    - "{{ workspace_repos.repos | default([]) }}"
