---
- name: Set selinux to permissive mode
  selinux:
    policy: targeted
    state: permissive

- include: dotfiles.yml
  tags: ["dotfiles"]
  become: yes
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Install pip3 packages
  pip: name='{{ pip_packages }}' state=latest executable=pip3

- name: NOPASSWD sudo
  lineinfile: "dest=/etc/sudoers.d/{{ ansible_env.SUDO_USER }} 
    create=yes state=present mode=0440
    owner=root group=root
    line='{{ ansible_env.USERNAME }} ALL=(ALL) NOPASSWD: ALL'"

- name: Change user shell to zsh
  user: name={{ ansible_env.USERNAME }} 
    state=present shell=/usr/bin/zsh 
